#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# ──────────────────────────────────────────────────────────────────────────
# 报告与截图都落在桌面这个文件夹里，最后整体拷回 Windows 给 AI 看。
# ENV_FILE 指向同一个目录：ask 会记住上次的答案，重跑不用重填。
# ──────────────────────────────────────────────────────────────────────────
REPORT_DIR="$HOME/Desktop/wxcsm-验收"
REPORT="$REPORT_DIR/验收报告.md"
mkdir -p "$REPORT_DIR"
ENV_FILE="$REPORT_DIR/.answers"

h2() { printf '\n## %s\n\n' "$1" >> "$REPORT"; }
kv() { printf -- '- **%s**：%s\n' "$1" "$2" >> "$REPORT"; }

# verdict KEY "问题"：y/N 记进报告与 .answers。刻意总是返回 0，
# 否则脚本会被 set -e 直接中断（问到"未通过"就不该继续崩掉）。
verdict() {
  local key="$1" q="$2" v
  if confirm "$q"; then v="通过 ✅"; else v="未通过 ❌"; fi
  printf -v "$key" '%s' "$v"
  write_env "$key" "$v"
}

verdict_note() {   # verdict_note KEY "问题" "补充说明提示"
  local key="$1" q="$2" hint="$3"
  verdict "$key" "$q"
  local extra
  ask "${key}_补充" "$hint"
}

# 出问题时才需要的兜底：把启动崩溃日志找出来一起打包。
collect_crashlog() {
  local f
  f=$(find /Applications "$HOME/Desktop" -maxdepth 6 \
        -name '绿泡泡聊天记录总结崩溃.log' 2>/dev/null | head -1)
  if [[ -n "$f" ]]; then
    cp "$f" "$REPORT_DIR/启动崩溃日志.log" 2>/dev/null || true
    note "找到崩溃日志并已复制：$f"
  else
    note "（没有崩溃日志，说明启动没崩 —— 这是好事）"
  fi
}

cat > "$REPORT" <<EOF
# 绿泡泡聊天记录总结 · macOS 版验收报告

- **验收时间**：$(date '+%Y-%m-%d %H:%M:%S')
- **机器/系统**：$(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo '?') / $(sw_vers -productVersion 2>/dev/null || echo '?')
- **CPU 架构**：$(uname -m)   ← 本包是 arm64 专用，Intel Mac 上应当打不开

> 截图请直接放进本文件夹（文件名随意，建议 01_xxx.png、02_xxx.png 这样排队）。
EOF

banner "绿泡泡聊天记录总结 · macOS 版验收"

# ──────────────────────────────────────────────────────────────────────────
stage "装到「应用程序」，不要从 dmg 里直接跑"
# 未签名 + 从网络下载 = 带隔离标记(quarantine)，Gatekeeper 会拦。
# 表现是「已损坏，无法打开。你应该将它移到废纸篓」—— 那不是文件坏了，
# 清掉隔离标记即可。放在显眼位置是因为几乎每个用户第一次都会撞上。
note "如果双击 dmg 弹「已损坏，无法打开」或「无法检查是否包含恶意软件」："
note "那不是文件坏了 —— 是未签名 + 隔离标记。在终端执行（文件名按实际改）："
note "    xattr -cr ~/Downloads/绿泡泡聊天记录总结-<架构>.dmg"
say "双击 .dmg，把「绿泡泡聊天记录总结.app」拖进「应用程序」。"
note "为什么强调这一条：程序启动失败时会把崩溃日志写在**自己旁边**；"
note "而 dmg 挂载出来是只读的，从那里跑的话日志写不出来 —— 出了问题我就没线索了。"
note "如果 .app 双击报「无法验证开发者」，同样处理："
note "    xattr -cr \"/Applications/绿泡泡聊天记录总结.app\""
step "首次打开若仍被拦：右键点 .app →「打开」→ 再点「打开」；或到 系统设置 → 隐私与安全性 →「仍要打开」。"
pause "装好了吗？（装好按回车）"
h2 "1. 安装"
verdict_note V1_安装 "打开后窗口正常出现、没有一闪而过？" "如果没出现，描述一下现象（没反应/闪退/报错弹窗）："

# ──────────────────────────────────────────────────────────────────────────
stage "确认版本号"
say "看窗口最上面的标题栏。"
step "标题应当是：绿泡泡聊天记录总结  v2.2.0（后面括号里是构建标记）"
verdict_note V2_版本 "标题栏里能看到 v2.2.0？" "如果不是，把你看到的标题照抄下来："

# ──────────────────────────────────────────────────────────────────────────
stage "用内置样例跑通，并导出 Excel"
say "这一步验的是核心链路 + packaged 的 openpyxl 真能用（CI 验不到这一层）。"
step "① 选择聊天记录来源 → 选「内置样例」（demo）"
step "② 点「加载聊天对象」→ 勾上一个"
step "③ 时间范围 → 点「近 30 天」或「本月」"
step "④ 生成内容 → 选「两者都要」"
step "⑤ Excel 保存位置 → 存到桌面，命名为 mac_demo.xlsx"
step "⑥ 点「开始提取并生成总结」"
pause "跑完了？（结果出现在 ⑥ 表格里后按回车）"
verdict_note V3_生成 "⑥ 结果区里出现了内容？" "如果报错了，把弹窗里的文字照抄下来："

XLSX="$HOME/Desktop/mac_demo.xlsx"
if [[ -f "$XLSX" ]]; then
  note "找到导出文件，正在核对里面的 sheet（用 unzip 读，不依赖任何 Python 库）…"
  SHEETS=$(unzip -p "$XLSX" xl/workbook.xml 2>/dev/null | grep -o 'name="[^"]*"' | sed 's/name=//; s/"//g' | paste -sd'、' -)
  note "文件里的 sheet：$SHEETS"
  kv "导出 Excel 的 sheet" "${SHEETS:-未读到}"
  if [[ "$SHEETS" == *"客户沟通总结"* && "$SHEETS" == *"客户问题答复清单"* ]]; then
    write_env V3b_双表 "通过 ✅（两个 sheet 都在）"
    note "两个 sheet 都在 ✅（客户沟通总结 + 客户问题答复清单）"
  else
    write_env V3b_双表 "未通过 ❌（只读到：$SHEETS）"
    warn "两个 sheet 没同时出现 —— 这正是需要反馈回来的情况"
  fi
else
  write_env V3b_双表 "未验证 ⚠（桌面上没找到 mac_demo.xlsx）"
  warn "桌面没找到 mac_demo.xlsx，请确认导出路径确实是桌面"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "我方成员窗口：勾选好不好用（重点）"
say "这一项是上次你反馈「不好用」的地方，现在专门验。"
step "点「我方成员 → 选择…」打开选择窗口。"
step "先随便点一行 → 看它有没有勾上（☑）。"
verdict_note V4_一次点击 "点一次就勾上了（不需要点两次）？" "如果不是，描述成什么样："
step "再点**另一行**。"
verdict_note V4_点哪行 "勾上的是你刚点的那一行（不是上一次点的那行）？" "如果不是，说说勾到了哪一行："
step "点「全选」，再点「全不选」。"
verdict_note V4_全选 "全选把整表都勾上、全不选把整表都清掉了？" "如果不是，描述一下："
step "看窗口底部的汇总行。"
verdict_note V4_汇总行 "汇总行显示「已选 N 人：…」（N 跟着勾选变化）？" "如果不是，照抄你看到的那行字："

# ──────────────────────────────────────────────────────────────────────────
stage "导出 Excel 模版"
step "在「名称库」那一行点「导出 Excel 模版」，存到桌面。"
step "用 Numbers / Excel 打开它。"
verdict_note V5_带出名字 "「姓名」列里**已经填着名称库里的人**（不是空模版）？" "如果不是，说说你看到什么："
verdict_note V5_红色表头 "「姓名（必填）」这个表头是**红色**的？" "如果不是，描述一下表头样子："

# ──────────────────────────────────────────────────────────────────────────
stage "导入模版：以文件为准 + 删人前先确认"
say "接着上一步那份模版改：删掉一行、再在下面加一个新名字，保存。"
step "回到选择窗口，点「导入 Excel…」，选刚才那份模版。"
step "在「选择姓名列」对话框里点「导入这些名字」。"
verdict_note V6_确认框 "弹出了一个**列出将要新增/移除谁**的确认框？" "如果不是，描述发生了什么："
step "点「确认」。"
verdict_note V6_以文件为准 "确认后，表里变成的正是模版里那批人（被删的那行没了、新加的进来了）？" "如果不是，说说现在的名单："

# ──────────────────────────────────────────────────────────────────────────
stage "收尾：收集诊断，生成报告"
say "最后把所有线索打包好。"
collect_crashlog

h2 "诊断信息（自动收集）"
{
  echo '```'
  echo "\$ sw_vers";            sw_vers 2>/dev/null || true
  echo "\$ uname -m";           uname -m
  echo "\$ 硬件";               system_profiler SPHardwareDataType 2>/dev/null | sed -n '3,8p'
  echo "\$ 包内版本";           defaults read "/Applications/绿泡泡聊天记录总结.app/Contents/Info.plist" CFBundleShortVersionString 2>/dev/null || echo '(读不到)'
  echo "\$ Gatekeeper";         spctl -a -vv "/Applications/绿泡泡聊天记录总结.app" 2>&1 | head -3
  echo '```'
} >> "$REPORT"

h2 "结论"
FAILED=$(grep -c '未通过' "$ENV_FILE" 2>/dev/null || echo 0)
UNVER=$(grep -c '未验证' "$ENV_FILE" 2>/dev/null || echo 0)
if [[ "$FAILED" == "0" && "$UNVER" == "0" ]]; then
  printf '全部检查通过 ✅\n' >> "$REPORT"
else
  printf '有 **%s** 项未通过、**%s** 项未验证 ❌ —— 详见上面的逐项结论。\n' "$FAILED" "$UNVER" >> "$REPORT"
fi

finish

printf '\n%s报告已生成：%s%s\n' "$BOLD" "$REPORT" "$RESET"
printf '%s截图请放进：%s%s\n\n' "$BOLD" "$REPORT_DIR" "$RESET"
printf '%s把整个文件夹交给 AI：%s\n' "$BOLD" "$RESET"
printf -- '  · 用共享文件夹 / U 盘 / 网盘，把 %s 整个目录拷到约定的接收目录\n' "$REPORT_DIR"
printf -- '  · 或者把「验收报告.md」的内容直接粘到对话里（截图单独发）\n\n'
